let okmreport_translations = {
    "en": {
        library: "Library code",
        collection_holdingbranch_total: "Collections (location): Total",
        collection_holdingbranch_books_total: "Collections (location): Books Total",
        collection_holdingbranch_books_finnish: "Collections (location): Books Finnish",
        collection_holdingbranch_books_swedish: "Collections (location): Books Swedish",
        collection_holdingbranch_books_sami: "Collections (location): Books Sámi",
        collection_holdingbranch_books_other_lang: "Collections (location): Books Other Languages",
        collection_holdingbranch_books_fiction_adult: "Collections (location): Books Fiction, Adults",
        collection_holdingbranch_books_fiction_juvenile: "Collections (location): Books Fiction, Children",
        collection_holdingbranch_books_fact_adult: "Collections (location): Books Non-fiction, Adults",
        collection_holdingbranch_books_fact_juvenile: "Collections (location): Books Non-fiction, Children",
        collection_holdingbranch_sheet_music_score: "Collections (location): Sheet Music and Scores",
        collection_holdingbranch_musical_recordings: "Collections (location): Musical Recordings",
        collection_holdingbranch_other_recordings: "Collections (location): Other Recordings",
        collection_holdingbranch_videos: "Collections (location): Videos",
        collection_holdingbranch_celia: "Collections (location): Celia",
        collection_holdingbranch_other: "Collections (location): Other Materials",
        collection_homebranch_total: "Collections (home): Total",
        collection_homebranch_books_total: "Collections (home): Books Total",
        collection_homebranch_books_finnish: "Collections (home): Books Finnish",
        collection_homebranch_books_swedish: "Collections (home): Books Swedish",
        collection_homebranch_books_sami: "Collections (home): Books Sámi",
        collection_homebranch_books_other_lang: "Collections (home): Books Other Languages",
        collection_homebranch_books_fiction_adult: "Collections (home): Books Fiction, Adults",
        collection_homebranch_books_fiction_juvenile: "Collections (home): Books Fiction, Children",
        collection_homebranch_books_fact_adult: "Collections (home): Books Non-fiction, Adults",
        collection_homebranch_books_fact_juvenile: "Collections (home): Books Non-fiction, Children",
        collection_homebranch_sheet_music_score: "Collections (home): Sheet Music and Scores",
        collection_homebranch_musical_recordings: "Collections (home): Musical Recordings",
        collection_homebranch_other_recordings: "Collections (home): Other Recordings",
        collection_homebranch_videos: "Collections (home): Videos",
        collection_homebranch_celia: "Collections (home): Celia",
        collection_homebranch_other: "Collections (home): Other Materials",
        acquisitions_total: "Acquisitions: Total",
        acquisitions_books_total: "Acquisitions: Books Total",
        acquisitions_books_finnish: "Acquisitions: Books Finnish",
        acquisitions_books_swedish: "Acquisitions: Books Swedish",
        acquisitions_books_sami: "Acquisitions: Books Sámi",
        acquisitions_books_other_lang: "Acquisitions: Books Other Languages",
        acquisitions_books_fiction_adult: "Acquisitions: Books Fiction, Adults",
        acquisitions_books_fiction_juvenile: "Acquisitions: Books Fiction, Children",
        acquisitions_books_fact_adult: "Acquisitions: Books Non-fiction, Adults",
        acquisitions_books_fact_juvenile: "Acquisitions: Books Non-fiction, Children",
        acquisitions_sheet_music_score: "Acquisitions: Sheet Music and Scores",
        acquisitions_musical_recordings: "Acquisitions: Musical Recordings",
        acquisitions_celia: "Acquisitions: Celia",
        acquisitions_other_recordings: "Acquisitions: Other Recordings",
        acquisitions_videos: "Acquisitions: Videos",
        acquisitions_other: "Acquisitions: Other Materials",
        acquisitions_expenditures: "Acquisition Costs: Total",
        acquisitions_expenditures_books: "Acquisition Costs: Books",
        issues_total: "Checkouts: Total",
        issues_books_total: "Checkouts: Books Total",
        issues_books_finnish: "Checkouts: Books Finnish",
        issues_books_swedish: "Checkouts: Books Swedish",
        issues_books_sami: "Checkouts: Books Sámi",
        issues_books_other_lang: "Checkouts: Books Other Languages",
        issues_books_fiction_adult: "Checkouts: Books Fiction, Adults",
        issues_books_fiction_juvenile: "Checkouts: Books Fiction, Children",
        issues_books_fact_adult: "Checkouts: Books Non-fiction, Adults",
        issues_books_fact_juvenile: "Checkouts: Books Non-fiction, Children",
        issues_sheet_music_score: "Checkouts: Sheet Music and Scores",
        issues_musical_recordings: "Checkouts: Musical Recordings",
        issues_celia: "Checkouts: Celia",
        issues_other_recordings: "Checkouts: Other Recordings",
        issues_videos: "Checkouts: Videos",
        issues_other: "Checkouts: Other Materials",
        issues_renews: "Checkouts: Renewals",
        interlibrary_loans_total: "Interlibrary Loans: Total",
        interlibrary_loans_books_total: "Interlibrary Loans: Books Total",
        interlibrary_loans_books_finnish: "Interlibrary Loans: Books Finnish",
        interlibrary_loans_books_swedish: "Interlibrary Loans: Books Swedish",
        interlibrary_loans_books_sami: "Interlibrary Loans: Books Sámi",
        interlibrary_loans_books_other_lang: "Interlibrary Loans: Books Other Languages",
        interlibrary_loans_books_fiction_adult: "Interlibrary Loans: Books Fiction, Adults",
        interlibrary_loans_books_fiction_juvenile: "Interlibrary Loans: Books Fiction, Children",
        interlibrary_loans_books_fact_adult: "Interlibrary Loans: Books Non-fiction, Adults",
        interlibrary_loans_books_fact_juvenile: "Interlibrary Loans: Books Non-fiction, Children",
        interlibrary_loans_sheet_music_score: "Interlibrary Loans: Sheet Music and Scores",
        interlibrary_loans_musical_recordings: "Interlibrary Loans: Musical Recordings",
        interlibrary_loans_celia: "Interlibrary Loans: Celia",
        interlibrary_loans_other_recordings: "Interlibrary Loans: Other Recordings",
        interlibrary_loans_videos: "Interlibrary Loans: Videos",
        interlibrary_loans_other: "Interlibrary Loans: Other Materials",
        deleted_total: "Deletions",
        active_borrowers: "Active patrons",
        celia_borrowers: "Celia patrons",
    },
    "fi": {
        library: "Kirjastotunnus",
        collection_holdingbranch_total: "Kokoelmat (sijainti): Yhteensä",
        collection_holdingbranch_books_total: "Kokoelmat (sijainti): Kirjat Yhteensä",
        collection_holdingbranch_books_finnish: "Kokoelmat (sijainti): Kirjat Suomenkieliset",
        collection_holdingbranch_books_swedish: "Kokoelmat (sijainti): Kirjat Ruotsinkieliset",
        collection_holdingbranch_books_sami: "Kokoelmat (sijainti): Kirjat Saamenkieliset",
        collection_holdingbranch_books_other_lang: "Kokoelmat (sijainti): Kirjat Muunkieliset",
        collection_holdingbranch_books_fiction_adult: "Kokoelmat (sijainti): Kirjat Kaunokirjat, aikuiset",
        collection_holdingbranch_books_fiction_juvenile: "Kokoelmat (sijainti): Kirjat Kaunokirjat, lapset",
        collection_holdingbranch_books_fact_adult: "Kokoelmat (sijainti): Kirjat Tietokirjat, aikuiset",
        collection_holdingbranch_books_fact_juvenile: "Kokoelmat (sijainti): Kirjat Tietokirjat, lapset",
        collection_holdingbranch_sheet_music_score: "Kokoelmat (sijainti): Nuotit ja partituurit",
        collection_holdingbranch_musical_recordings: "Kokoelmat (sijainti): Musiikkiäänitteet",
        collection_holdingbranch_other_recordings: "Kokoelmat (sijainti): Muut äänitteet",
        collection_holdingbranch_videos: "Kokoelmat (sijainti): Videotallenteet",
        collection_holdingbranch_celia: "Kokoelmat (sijainti): Celia",
        collection_holdingbranch_other: "Kokoelmat (sijainti): Muut aineistot",
        collection_homebranch_total: "Kokoelmat (koti): Yhteensä",
        collection_homebranch_books_total: "Kokoelmat (koti): Kirjat Yhteensä",
        collection_homebranch_books_finnish: "Kokoelmat (koti): Kirjat Suomenkieliset",
        collection_homebranch_books_swedish: "Kokoelmat (koti): Kirjat Ruotsinkieliset",
        collection_homebranch_books_sami: "Kokoelmat (koti): Kirjat Saamenkieliset",
        collection_homebranch_books_other_lang: "Kokoelmat (koti): Kirjat Muunkieliset",
        collection_homebranch_books_fiction_adult: "Kokoelmat (koti): Kirjat Kaunokirjat, aikuiset",
        collection_homebranch_books_fiction_juvenile: "Kokoelmat (koti): Kirjat Kaunokirjat, lapset",
        collection_homebranch_books_fact_adult: "Kokoelmat (koti): Kirjat Tietokirjat, aikuiset",
        collection_homebranch_books_fact_juvenile: "Kokoelmat (koti): Kirjat Tietokirjat, lapset",
        collection_homebranch_sheet_music_score: "Kokoelmat (koti): Nuotit ja partituurit",
        collection_homebranch_musical_recordings: "Kokoelmat (koti): Musiikkiäänitteet",
        collection_homebranch_other_recordings: "Kokoelmat (koti): Muut äänitteet",
        collection_homebranch_videos: "Kokoelmat (koti): Videotallenteet",
        collection_homebranch_celia: "Kokoelmat (koti): Celia",
        collection_homebranch_other: "Kokoelmat (koti): Muut aineistot",
        acquisitions_total: "Hankinnat: Yhteensä",
        acquisitions_books_total: "Hankinnat: Kirjat Yhteensä",
        acquisitions_books_finnish: "Hankinnat: Kirjat Suomenkieliset",
        acquisitions_books_swedish: "Hankinnat: Kirjat Ruotsinkieliset",
        acquisitions_books_sami: "Hankinnat: Kirjat Saamenkieliset",
        acquisitions_books_other_lang: "Hankinnat: Kirjat Muunkieliset",
        acquisitions_books_fiction_adult: "Hankinnat: Kirjat Kaunokirjat, aikuiset",
        acquisitions_books_fiction_juvenile: "Hankinnat: Kirjat Kaunokirjat, lapset",
        acquisitions_books_fact_adult: "Hankinnat: Kirjat Tietokirjat, aikuiset",
        acquisitions_books_fact_juvenile: "Hankinnat: Kirjat Tietokirjat, lapset",
        acquisitions_sheet_music_score: "Hankinnat: Nuotit ja partituurit",
        acquisitions_musical_recordings: "Hankinnat: Musiikkiäänitteet",
        acquisitions_celia: "Hankinnat: Celia",
        acquisitions_other_recordings: "Hankinnat: Muut äänitteet",
        acquisitions_videos: "Hankinnat: Videotallenteet",
        acquisitions_other: "Hankinnat: Muut aineistot",
        acquisitions_expenditures: "Hankintakulut: Yhteensä",
        acquisitions_expenditures_books: "Hankintakulut: Kirjat",
        issues_total: "Lainaus: Yhteensä",
        issues_books_total: "Lainaus: Kirjat Yhteensä",
        issues_books_finnish: "Lainaus: Kirjat Suomenkieliset",
        issues_books_swedish: "Lainaus: Kirjat Ruotsinkieliset",
        issues_books_sami: "Lainaus: Kirjat Saamenkieliset",
        issues_books_other_lang: "Lainaus: Kirjat Muunkieliset",
        issues_books_fiction_adult: "Lainaus: Kirjat Kaunokirjat, aikuiset",
        issues_books_fiction_juvenile: "Lainaus: Kirjat Kaunokirjat, lapset",
        issues_books_fact_adult: "Lainaus: Kirjat Tietokirjat, aikuiset",
        issues_books_fact_juvenile: "Lainaus: Kirjat Tietokirjat, lapset",
        issues_sheet_music_score: "Lainaus: Nuotit ja partituurit",
        issues_musical_recordings: "Lainaus: Musiikkiäänitteet",
        issues_celia: "Lainaus: Celia",
        issues_other_recordings: "Lainaus: Muut äänitteet",
        issues_videos: "Lainaus: Videotallenteet",
        issues_other: "Lainaus: Muut aineistot",
        issues_renews: "Lainaus: Uusinnat",
        interlibrary_loans_total: "Kaukolainaus: Yhteensä",
        interlibrary_loans_books_total: "Kaukolainaus: Kirjat Yhteensä",
        interlibrary_loans_books_finnish: "Kaukolainaus: Kirjat Suomenkieliset",
        interlibrary_loans_books_swedish: "Kaukolainaus: Kirjat Ruotsinkieliset",
        interlibrary_loans_books_sami: "Kaukolainaus: Kirjat Saamenkieliset",
        interlibrary_loans_books_other_lang: "Kaukolainaus: Kirjat Muunkieliset",
        interlibrary_loans_books_fiction_adult: "Kaukolainaus: Kirjat Kaunokirjat, aikuiset",
        interlibrary_loans_books_fiction_juvenile: "Kaukolainaus: Kirjat Kaunokirjat, lapset",
        interlibrary_loans_books_fact_adult: "Kaukolainaus: Kirjat Tietokirjat, aikuiset",
        interlibrary_loans_books_fact_juvenile: "Kaukolainaus: Kirjat Tietokirjat, lapset",
        interlibrary_loans_sheet_music_score: "Kaukolainaus: Nuotit ja partituurit",
        interlibrary_loans_musical_recordings: "Kaukolainaus: Musiikkiäänitteet",
        interlibrary_loans_celia: "Kaukolainaus: Celia",
        interlibrary_loans_other_recordings: "Kaukolainaus: Muut äänitteet",
        interlibrary_loans_videos: "Kaukolainaus: Videotallenteet",
        interlibrary_loans_other: "Kaukolainaus: Muut aineistot",
        deleted_total: "Poistot",
        active_borrowers: "Aktiiviset asiakkaat",
        celia_borrowers: "Celia-lainaajat",
    },
    "sv": {
        library: "Bibliotekskod",
        collection_holdingbranch_total: "Samlingar (plats): Totalt",
        collection_holdingbranch_books_total: "Samlingar (plats): Böcker Totalt",
        collection_holdingbranch_books_finnish: "Samlingar (plats): Böcker Svenska",
        collection_holdingbranch_books_swedish: "Samlingar (plats): Böcker Svenska",
        collection_holdingbranch_books_sami: "Samlingar (plats): Böcker Samiska",
        collection_holdingbranch_books_other_lang: "Samlingar (plats): Böcker Andra språk",
        collection_holdingbranch_books_fiction_adult: "Samlingar (plats): Böcker Skönlitteratur, Vuxna",
        collection_holdingbranch_books_fiction_juvenile: "Samlingar (plats): Böcker Skönlitteratur, Barn",
        collection_holdingbranch_books_fact_adult: "Samlingar (plats): Böcker Facklitteratur, Vuxna",
        collection_holdingbranch_books_fact_juvenile: "Samlingar (plats): Böcker Facklitteratur, Barn",
        collection_holdingbranch_sheet_music_score: "Samlingar (plats): Notblad och partiturer",
        collection_holdingbranch_musical_recordings: "Samlingar (plats): Musikinspelningar",
        collection_holdingbranch_other_recordings: "Samlingar (plats): Andra inspelningar",
        collection_holdingbranch_videos: "Samlingar (plats): Videor",
        collection_holdingbranch_celia: "Samlingar (plats): Celia",
        collection_holdingbranch_other: "Samlingar (plats): Annat material",
        collection_homebranch_total: "Samlingar (hem): Totalt",
        collection_homebranch_books_total: "Samlingar (hem): Böcker Totalt",
        collection_homebranch_books_finnish: "Samlingar (hem): Böcker Finska",
        collection_homebranch_books_swedish: "Samlingar (hem): Böcker Svenska",
        collection_homebranch_books_sami: "Samlingar (hem): Böcker Samiska",
        collection_homebranch_books_other_lang: "Samlingar (hem): Böcker Andra språk",
        collection_homebranch_books_fiction_adult: "Samlingar (hem): Böcker Skönlitteratur, Vuxna",
        collection_homebranch_books_fiction_juvenile: "Samlingar (hem): Böcker Skönlitteratur, Barn",
        collection_homebranch_books_fact_adult: "Samlingar (hem): Böcker Facklitteratur, Vuxna",
        collection_homebranch_books_fact_juvenile: "Samlingar (hem): Böcker Facklitteratur, Barn",
        collection_homebranch_sheet_music_score: "Samlingar (hem): Notblad och partiturer",
        collection_homebranch_musical_recordings: "Samlingar (hem): Musikinspelningar",
        collection_homebranch_other_recordings: "Samlingar (hem): Andra inspelningar",
        collection_homebranch_videos: "Samlingar (hem): Videor",
        collection_homebranch_celia: "Samlingar (hem): Celia",
        collection_homebranch_other: "Samlingar (hem): Annat material",
        acquisitions_total: "Inköp: Totalt",
        acquisitions_books_total: "Inköp: Böcker Totalt",
        acquisitions_books_finnish: "Inköp: Böcker Finska",
        acquisitions_books_swedish: "Inköp: Böcker Svenska",
        acquisitions_books_sami: "Inköp: Böcker Samiska",
        acquisitions_books_other_lang: "Inköp: Böcker Andra språk",
        acquisitions_books_fiction_adult: "Inköp: Böcker Skönlitteratur, Vuxna",
        acquisitions_books_fiction_juvenile: "Inköp: Böcker Skönlitteratur, Barn",
        acquisitions_books_fact_adult: "Inköp: Böcker Facklitteratur, Vuxna",
        acquisitions_books_fact_juvenile: "Inköp: Böcker Facklitteratur, Barn",
        acquisitions_sheet_music_score: "Inköp: Notblad och partiturer",
        acquisitions_musical_recordings: "Inköp: Musikinspelningar",
        acquisitions_celia: "Inköp: Celia",
        acquisitions_other_recordings: "Inköp: Andra inspelningar",
        acquisitions_videos: "Inköp: Videor",
        acquisitions_other: "Inköp: Annat material",
        acquisitions_expenditures: "Inköpsutgifter: Totalt",
        acquisitions_expenditures_books: "Inköpsutgifter: Böcker",
        issues_total: "Lån: Totalt",
        issues_books_total: "Lån: Böcker Totalt",
        issues_books_finnish: "Lån: Böcker Finska",
        issues_books_swedish: "Lån: Böcker Svenska",
        issues_books_sami: "Lån: Böcker Samiska",
        issues_books_other_lang: "Lån: Böcker Andra språk",
        issues_books_fiction_adult: "Lån: Böcker Skönlitteratur, Vuxna",
        issues_books_fiction_juvenile: "Lån: Böcker Skönlitteratur, Barn",
        issues_books_fact_adult: "Lån: Böcker Facklitteratur, Vuxna",
        issues_books_fact_juvenile: "Lån: Böcker Facklitteratur, Barn",
        issues_sheet_music_score: "Lån: Notblad och partiturer",
        issues_musical_recordings: "Lån: Musikinspelningar",
        issues_celia: "Lån: Celia",
        issues_other_recordings: "Lån: Andra inspelningar",
        issues_videos: "Lån: Videor",
        issues_other: "Lån: Annat material",
        issues_renews: "Lån: Förnyelser",
        interlibrary_loans_total: "Fjärrlån: Totalt",
        interlibrary_loans_books_total: "Fjärrlån: Böcker Totalt",
        interlibrary_loans_books_finnish: "Fjärrlån: Böcker Finska",
        interlibrary_loans_books_swedish: "Fjärrlån: Böcker Svenska",
        interlibrary_loans_books_sami: "Fjärrlån: Böcker Samiska",
        interlibrary_loans_books_other_lang: "Fjärrlån: Böcker Andra språk",
        interlibrary_loans_books_fiction_adult: "Fjärrlån: Böcker Skönlitteratur, Vuxna",
        interlibrary_loans_books_fiction_juvenile: "Fjärrlån: Böcker Skönlitteratur, Barn",
        interlibrary_loans_books_fact_adult: "Fjärrlån: Böcker Facklitteratur, Vuxna",
        interlibrary_loans_books_fact_juvenile: "Fjärrlån: Böcker Facklitteratur, Barn",
        interlibrary_loans_sheet_music_score: "Fjärrlån: Notblad och partiturer",
        interlibrary_loans_musical_recordings: "Fjärrlån: Musikinspelningar",
        interlibrary_loans_celia: "Fjärrlån: Celia",
        interlibrary_loans_other_recordings: "Fjärrlån: Andra inspelningar",
        interlibrary_loans_videos: "Fjärrlån: Videor",
        interlibrary_loans_other: "Fjärrlån: Annat material",
        deleted_total: "Raderingar",
        active_borrowers: "Aktiva låntagare",
        celia_borrowers: "Celia-låntagare",
    }
}

function lt(key, ...args) {
  // Detect language, default to 'en'
  const lang = (language || "en").substring(0,2);
  const dict = okmreport_translations[lang] ||  okmreport_translations["en"];
  const val = dict[key];
  return typeof val === "function" ? val(...args) : val;
}

let okmfields = [
    {
        label: lt("library"),
        key: "library",
        sortable: true,
        stickyColumn: true,
        isRowHeader: true,
        variant: "success",
      },


        { label: lt("collection_holdingbranch_total"), key: "collection_by_holdingbranch.total", sortable: true, variant: 'success'},
        { label: lt("collection_holdingbranch_books_total"), key: "collection_by_holdingbranch.books_total" , sortable: true },
        { label: lt("collection_holdingbranch_books_finnish"), key: "collection_by_holdingbranch.books_finnish" , sortable: true, },
        { label: lt("collection_holdingbranch_books_swedish"), key: "collection_by_holdingbranch.books_swedish" , sortable: true, },
        { label: lt("collection_holdingbranch_books_sami"), key: "collection_by_holdingbranch.books_sami" , sortable: true, },
        { label: lt("collection_holdingbranch_books_other_lang"), key: "collection_by_holdingbranch.books_other_lang" , sortable: true, },
        { label: lt("collection_holdingbranch_books_fiction_adult"), key: "collection_by_holdingbranch.books_fiction_adult" , sortable: true, },
        { label: lt("collection_holdingbranch_books_fiction_juvenile"), key: "collection_by_holdingbranch.books_fiction_juvenile" , sortable: true, },
        { label: lt("collection_holdingbranch_books_fact_adult"), key: "collection_by_holdingbranch.books_fact_adult" , sortable: true, },
        { label: lt("collection_holdingbranch_books_fact_juvenile"), key: "collection_by_holdingbranch.books_fact_juvenile" , sortable: true, },
        { label: lt("collection_holdingbranch_sheet_music_score"), key: "collection_by_holdingbranch.sheet_music_score" , sortable: true, },
        { label: lt("collection_holdingbranch_musical_recordings"), key: "collection_by_holdingbranch.musical_recordings" , sortable: true, },
        { label: lt("collection_holdingbranch_other_recordings"), key: "collection_by_holdingbranch.other_recordings" , sortable: true, },
        { label: lt("collection_holdingbranch_videos"), key: "collection_by_holdingbranch.videos" , sortable: true, },
        { label: lt("collection_holdingbranch_celia"), key: "collection_by_holdingbranch.celia" , sortable: true, },
        { label: lt("collection_holdingbranch_other"), key: "collection_by_holdingbranch.other" , sortable: true, },

        { label: lt("collection_homebranch_total"), key: "collection_by_homebranch.total", sortable: true, variant: 'success'},
        { label: lt("collection_homebranch_books_total"), key: "collection_by_homebranch.books_total" , sortable: true, },
        { label: lt("collection_homebranch_books_finnish"), key: "collection_by_homebranch.books_finnish" , sortable: true, },
        { label: lt("collection_homebranch_books_swedish"), key: "collection_by_homebranch.books_swedish" , sortable: true, },
        { label: lt("collection_homebranch_books_sami"), key: "collection_by_homebranch.books_sami" , sortable: true, },
        { label: lt("collection_homebranch_books_other_lang"), key: "collection_by_homebranch.books_other_lang" , sortable: true, },
        { label: lt("collection_homebranch_books_fiction_adult"), key: "collection_by_homebranch.books_fiction_adult" , sortable: true, },
        { label: lt("collection_homebranch_books_fiction_juvenile"), key: "collection_by_homebranch.books_fiction_juvenile" , sortable: true, },
        { label: lt("collection_homebranch_books_fact_adult"), key: "collection_by_homebranch.books_fact_adult" , sortable: true, },
        { label: lt("collection_homebranch_books_fact_juvenile"), key: "collection_by_homebranch.books_fact_juvenile" , sortable: true, },
        { label: lt("collection_homebranch_sheet_music_score"), key: "collection_by_homebranch.sheet_music_score" , sortable: true, },
        { label: lt("collection_homebranch_musical_recordings"), key: "collection_by_homebranch.musical_recordings" , sortable: true, },
        { label: lt("collection_homebranch_other_recordings"), key: "collection_by_homebranch.other_recordings" , sortable: true, },
        { label: lt("collection_homebranch_videos"), key: "collection_by_homebranch.videos" , sortable: true, },
        { label: lt("collection_homebranch_celia"), key: "collection_by_homebranch.celia" , sortable: true, },
        { label: lt("collection_homebranch_other"), key: "collection_by_homebranch.other" , sortable: true, },

        { label: lt("acquisitions_total"), key: "acquisitions.total" , sortable: true, variant: 'success'},
        { label: lt("acquisitions_books_total"), key: "acquisitions.books_total" , sortable: true,},
        { label: lt("acquisitions_books_finnish"), key: "acquisitions.books_finnish" , sortable: true,},
        { label: lt("acquisitions_books_swedish"), key: "acquisitions.books_swedish" , sortable: true,},
        { label: lt("acquisitions_books_sami"), key: "acquisitions.books_sami" , sortable: true,},
        { label: lt("acquisitions_books_other_lang"), key: "acquisitions.books_other_lang" , sortable: true,},
        { label: lt("acquisitions_books_fiction_adult"), key: "acquisitions.books_fiction_adult" , sortable: true,},
        { label: lt("acquisitions_books_fiction_juvenile"), key: "acquisitions.books_fiction_juvenile" , sortable: true,},
        { label: lt("acquisitions_books_fact_adult"), key: "acquisitions.books_fact_adult" , sortable: true,},
        { label: lt("acquisitions_books_fact_juvenile"), key: "acquisitions.books_fact_juvenile" , sortable: true,},
        { label: lt("acquisitions_sheet_music_score"), key: "acquisitions.sheet_music_score" , sortable: true,},
        { label: lt("acquisitions_musical_recordings"), key: "acquisitions.musical_recordings" , sortable: true,},
        { label: lt("acquisitions_celia"), key: "acquisitions.celia" , sortable: true,},
        { label: lt("acquisitions_other_recordings"), key: "acquisitions.other_recordings" , sortable: true,},
        { label: lt("acquisitions_videos"), key: "acquisitions.videos" , sortable: true,},
        { label: lt("acquisitions_other"), key: "acquisitions.other" , sortable: true,},

        { label: lt("acquisitions_expenditures"), key: "acquisitions.expenditures" , sortable: true, variant: 'success'},
        { label: lt("acquisitions_expenditures_books"), key: "acquisitions.expenditures_books" , sortable: true, variant: 'success'},

        { label: lt("issues_total"), key: "issues.total" , sortable: true, variant: 'success'},
        { label: lt("issues_books_total"), key: "issues.books_total" , sortable: true,},
        { label: lt("issues_books_finnish"), key: "issues.books_finnish" , sortable: true,},
        { label: lt("issues_books_swedish"), key: "issues.books_swedish" , sortable: true,},
        { label: lt("issues_books_sami"), key: "issues.books_sami" , sortable: true,},
        { label: lt("issues_books_other_lang"), key: "issues.books_other_lang" , sortable: true,},
        { label: lt("issues_books_fiction_adult"), key: "issues.books_fiction_adult" , sortable: true,},
        { label: lt("issues_books_fiction_juvenile"), key: "issues.books_fiction_juvenile" , sortable: true,},
        { label: lt("issues_books_fact_adult"), key: "issues.books_fact_adult" , sortable: true,},
        { label: lt("issues_books_fact_juvenile"), key: "issues.books_fact_juvenile" , sortable: true,},
        { label: lt("issues_sheet_music_score"), key: "issues.sheet_music_score" , sortable: true,},
        { label: lt("issues_musical_recordings"), key: "issues.musical_recordings" , sortable: true,},
        { label: lt("issues_celia"), key: "issues.celia" , sortable: true,},
        { label: lt("issues_other_recordings"), key: "issues.other_recordings" , sortable: true,},
        { label: lt("issues_videos"), key: "issues.videos" , sortable: true,},
        { label: lt("issues_other"), key: "issues.other" , sortable: true,},
        { label: lt("issues_renews"), key: "issues.renews", sortable: true},

        { label: lt("interlibrary_loans_total"), key: "interlibrary_loans.total" , sortable: true, variant: 'success'},
        { label: lt("interlibrary_loans_books_total"), key: "interlibrary_loans.books_total" , sortable: true,},
        { label: lt("interlibrary_loans_books_finnish"), key: "interlibrary_loans.books_finnish" , sortable: true,},
        { label: lt("interlibrary_loans_books_swedish"), key: "interlibrary_loans.books_swedish" , sortable: true,},
        { label: lt("interlibrary_loans_books_sami"), key: "interlibrary_loans.books_sami" , sortable: true,},
        { label: lt("interlibrary_loans_books_other_lang"), key: "interlibrary_loans.books_other_lang" , sortable: true,},
        { label: lt("interlibrary_loans_books_fiction_adult"), key: "interlibrary_loans.books_fiction_adult" , sortable: true,},
        { label: lt("interlibrary_loans_books_fiction_juvenile"), key: "interlibrary_loans.books_fiction_juvenile" , sortable: true,},
        { label: lt("interlibrary_loans_books_fact_adult"), key: "interlibrary_loans.books_fact_adult" , sortable: true,},
        { label: lt("interlibrary_loans_books_fact_juvenile"), key: "interlibrary_loans.books_fact_juvenile" , sortable: true,},
        { label: lt("interlibrary_loans_sheet_music_score"), key: "interlibrary_loans.sheet_music_score" , sortable: true,},
        { label: lt("interlibrary_loans_musical_recordings"), key: "interlibrary_loans.musical_recordings" , sortable: true,},
        { label: lt("interlibrary_loans_celia"), key: "interlibrary_loans.celia" , sortable: true,},
        { label: lt("interlibrary_loans_other_recordings"), key: "interlibrary_loans.other_recordings" , sortable: true,},
        { label: lt("interlibrary_loans_videos"), key: "interlibrary_loans.videos" , sortable: true,},
        { label: lt("interlibrary_loans_other"), key: "interlibrary_loans.other" , sortable: true,},

        //{ label: "Sanomalehdet", key: "serials.newspaper" , sortable: true, variant: 'info'},
        //{ label: "Aikakauslehdet", key: "serials.serials" , sortable: true,},

        { label: lt("deleted_total"), key: "deleted.total" , sortable: true, variant: 'success'},

        { label: lt("active_borrowers"), key: "active_borrowers" , sortable: true, variant: 'success'},
        { label: lt("celia_borrowers"), key: "celia_borrowers", sortable: true, variant: 'success'},
  ];

  //uusokmtest.json

  //näitä ei käytetä

//   "acquisitions": {
//     "expenditure_acquisitions_books": 2004.81,

//     "books_finnish": 0,

//     "itemtypes": {
//         "": 6,
//         "KONSOLIP": 9,
//         "CD": 11,
//         "NUOTTI": 2,
//         "DVD": 12,
//         "KIRJA": 116
//     },
//     "expenditure_acquisitions": 3509.23,

// },

//   "collection_by_holdingbranch": {
//     "": 2339,
//     "itemtypes": {
//         "NUOTTI": 156,
//         "DVD": 45,
//         "PUHECD": 238,
//         "KARTTA": 3,
//         "DIA": 2,
//         "ESINE": 1,
//         "KONSOLIP": 19,
//         "ATLAS": 4,
//         "KIRJA": 22528,
//         "CD": 192,
//         "MONIVIES": 84
//     },
   // "books_finnish": 0,
//},

// "issues": {

// },

// "serials": {
//   "serials": 0,
//   "total": 0,
//   "journals": 0,
//   "newspaper": 0
// },


//
